In [2]:
import numpy as np
import random
import csv

You can download the "Orthography vectors.txt" from our OSF page at https://osf.io/6mys9/ This file contains the pre-trained orthography vectors.

Alternatively, you can create the vectors directly from the "Make Orthography vectors" script included in the repository

In [3]:
# Load orthography vectors
with open('Orthography vectors.txt', 'r') as f:
    df = f.read()

In [4]:
#convert raw txt file into word list and matrix
df = df.split('\n')
df = [i.strip() for i in df]
word_list = []
word_matrix = []
for i in df:
    array = i.split(' ')
    word_list.append(array[0])
    word_vec = []
    for x in array[1:]:
        word_vec.append(float(x))
    word_matrix.append(word_vec)
word_matrix = np.array(word_matrix, dtype=np.float32)

In [5]:
# set up word dictionary to index rows of matrix by word
word_dic = {}
for i in range(0, len(word_list)):
    word_dic[word_list[i]] = i

In [6]:
import scipy.stats

def r_sq(x, y):
    cor = scipy.stats.pearsonr(x, y)
    return cor[0]**2

def mse(x, y):
    return np.sum((x - y)**2) / len(x)

In [7]:
def sel_second(x):
    return x[1]

In [8]:
def normalize_matrix(mat):
    sq_mat = mat**2
    sum_sq = np.sum(sq_mat, axis=1)
    mag = np.sqrt(sum_sq)
    mag[mag == 0] = 1
    normed_mat = np.transpose((np.transpose(mat) / mag))
    return normed_mat

In [9]:
def make_memory(word_list):
    mem = []
    for i in word_list:
        mem.append(word_matrix[word_dic[i]])
    return np.array(mem)

In [10]:
def echo_intensity(probes, memory, tau=3):
    normed_memory = normalize_matrix(memory)
    similarities = probes @ np.transpose(normed_memory)
    if tau == 2:
        activations = similarities*(abs(similarities))
    elif tau == 4:
        activations = similarities*(abs(similarities))*similarities*(abs(similarities))
    elif tau == 6:
        activations = similarities*(abs(similarities))*similarities*(abs(similarities))*similarities*(abs(similarities))
    else:
        activations = similarities**tau
    activations = np.sum(activations, axis=1)
    return activations

In [11]:
# study and test lists (version A)
test_a = [['KLENDER', 'crit_lure', 'related', '2', 'new'],
 ['SNENDER', 'list_item', 'related', '1', 'old'],
 ['NENDER', 'list_item', 'related', '1', 'old'],
 ['HENDER', 'list_item', 'related', '1', 'old'],
 ['DENDER', 'list_item', 'related', '1', 'old'],
 ['WENDER', 'list_item', 'related', '1', 'old'],
 ['TRENDER', 'list_item', 'related', '1', 'old'],
 ['DATOP', 'crit_lure', 'related', '2', 'new'],
 ['FRATOP', 'list_item', 'related', '1', 'old'],
 ['SATOP', 'list_item', 'related', '1', 'old'],
 ['DRATOP', 'list_item', 'related', '1', 'old'],
 ['TRATOP', 'list_item', 'related', '1', 'old'],
 ['TATOP', 'list_item', 'related', '1', 'old'],
 ['SNATOP', 'list_item', 'related', '1', 'old'],
 ['KIGIN', 'crit_lure', 'related', '2', 'new'],
 ['DRIGIN', 'list_item', 'related', '1', 'old'],
 ['TIGIN', 'list_item', 'related', '1', 'old'],
 ['PRIGIN', 'list_item', 'related', '1', 'old'],
 ['TRIGIN', 'list_item', 'related', '1', 'old'],
 ['DIGIN', 'list_item', 'related', '1', 'old'],
 ['HIGIN', 'list_item', 'related', '1', 'old'],
 ['VALKY', 'crit_lure', 'related', '2', 'new'],
 ['KLALKY', 'list_item', 'related', '1', 'old'],
 ['PHALKY', 'list_item', 'related', '1', 'old'],
 ['FLALKY', 'list_item', 'related', '1', 'old'],
 ['KRALKY', 'list_item', 'related', '1', 'old'],
 ['PRALKY', 'list_item', 'related', '1', 'old'],
 ['GALKY', 'list_item', 'related', '1', 'old'],
 ['SHEDI', 'crit_lure', 'related', '2', 'new'],
 ['PHEDI', 'list_item', 'related', '1', 'old'],
 ['NEDI', 'list_item', 'related', '1', 'old'],
 ['KEDI', 'list_item', 'related', '1', 'old'],
 ['BREDI', 'list_item', 'related', '1', 'old'],
 ['HEDI', 'list_item', 'related', '1', 'old'],
 ['KLEDI', 'list_item', 'related', '1', 'old'],
 ['PRESKTO', 'crit_lure', 'related', '2', 'new'],
 ['SHESKTO', 'list_item', 'related', '1', 'old'],
 ['JESKTO', 'list_item', 'related', '1', 'old'],
 ['GRESKTO', 'list_item', 'related', '1', 'old'],
 ['MESKTO', 'list_item', 'related', '1', 'old'],
 ['KLESKTO', 'list_item', 'related', '1', 'old'],
 ['SNESKTO', 'list_item', 'related', '1', 'old'],
 ['WECK', 'crit_lure', 'related', '2', 'new'],
 ['CRECK', 'list_item', 'related', '1', 'old'],
 ['BLECK', 'list_item', 'related', '1', 'old'],
 ['FRECK', 'list_item', 'related', '1', 'old'],
 ['BRECK', 'list_item', 'related', '1', 'old'],
 ['SNECK', 'list_item', 'related', '1', 'old'],
 ['TECK', 'list_item', 'related', '1', 'old'],
 ['HAPTE', 'crit_lure', 'related', '2', 'new'],
 ['BAPTE', 'list_item', 'related', '1', 'old'],
 ['DAPTE', 'list_item', 'related', '1', 'old'],
 ['VAPTE', 'list_item', 'related', '1', 'old'],
 ['SWAPTE', 'list_item', 'related', '1', 'old'],
 ['PRAPTE', 'list_item', 'related', '1', 'old'],
 ['BLAPTE', 'list_item', 'related', '1', 'old'],
 ['KLOOM', 'crit_lure', 'related', '2', 'new'],
 ['TROOM', 'list_item', 'related', '1', 'old'],
 ['FROOM', 'list_item', 'related', '1', 'old'],
 ['KROOM', 'list_item', 'related', '1', 'old'],
 ['FLOOM', 'list_item', 'related', '1', 'old'],
 ['SNOOM', 'list_item', 'related', '1', 'old'],
 ['VOOM', 'list_item', 'related', '1', 'old'],
 ['ZAISE', 'crit_lure', 'related', '2', 'new'],
 ['SAISE', 'list_item', 'related', '1', 'old'],
 ['VAISE', 'list_item', 'related', '1', 'old'],
 ['SNAISE', 'list_item', 'related', '1', 'old'],
 ['PAISE', 'list_item', 'related', '1', 'old'],
 ['JAISE', 'list_item', 'related', '1', 'old'],
 ['TAISE', 'list_item', 'related', '1', 'old'],
 ['TIFFY', 'crit_lure', 'unrelated', '2', 'new'],
 ['PRIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['TRIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['SIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['BLIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['ZIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['GRIFFY', 'list_item', 'unrelated', '2', 'new'],
 ['VUTER', 'crit_lure', 'unrelated', '2', 'new'],
 ['SNUTER', 'list_item', 'unrelated', '2', 'new'],
 ['PLUTER', 'list_item', 'unrelated', '2', 'new'],
 ['BRUTER', 'list_item', 'unrelated', '2', 'new'],
 ['HUTER', 'list_item', 'unrelated', '2', 'new'],
 ['KLUTER', 'list_item', 'unrelated', '2', 'new'],
 ['CRUTER', 'list_item', 'unrelated', '2', 'new'],
 ['FLEAGLE', 'crit_lure', 'unrelated', '2', 'new'],
 ['KLEAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['CREAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['PLEAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['GREAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['PREAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['SWEAGLE', 'list_item', 'unrelated', '2', 'new'],
 ['ZIQUE', 'crit_lure', 'unrelated', '2', 'new'],
 ['JIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['NIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['SHIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['PLIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['FRIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['WIQUE', 'list_item', 'unrelated', '2', 'new'],
 ['PRUSS', 'crit_lure', 'unrelated', '2', 'new'],
 ['DRUSS', 'list_item', 'unrelated', '2', 'new'],
 ['ZUSS', 'list_item', 'unrelated', '2', 'new'],
 ['NUSS', 'list_item', 'unrelated', '2', 'new'],
 ['KRUSS', 'list_item', 'unrelated', '2', 'new'],
 ['GRUSS', 'list_item', 'unrelated', '2', 'new'],
 ['KUSS', 'list_item', 'unrelated', '2', 'new'],
 ['KATION', 'crit_lure', 'unrelated', '2', 'new'],
 ['FRATION', 'list_item', 'unrelated', '2', 'new'],
 ['JATION', 'list_item', 'unrelated', '2', 'new'],
 ['KRATION', 'list_item', 'unrelated', '2', 'new'],
 ['SNATION', 'list_item', 'unrelated', '2', 'new'],
 ['PLATION', 'list_item', 'unrelated', '2', 'new'],
 ['GRATION', 'list_item', 'unrelated', '2', 'new'],
 ['SWOWEN', 'crit_lure', 'unrelated', '2', 'new'],
 ['KROWEN', 'list_item', 'unrelated', '2', 'new'],
 ['TOWEN', 'list_item', 'unrelated', '2', 'new'],
 ['POWEN', 'list_item', 'unrelated', '2', 'new'],
 ['TROWEN', 'list_item', 'unrelated', '2', 'new'],
 ['CLOWEN', 'list_item', 'unrelated', '2', 'new'],
 ['FROWEN', 'list_item', 'unrelated', '2', 'new'],
 ['KLUMME', 'crit_lure', 'unrelated', '2', 'new'],
 ['DUMME', 'list_item', 'unrelated', '2', 'new'],
 ['GRUMME', 'list_item', 'unrelated', '2', 'new'],
 ['PUMME', 'list_item', 'unrelated', '2', 'new'],
 ['WUMME', 'list_item', 'unrelated', '2', 'new'],
 ['SWUMME', 'list_item', 'unrelated', '2', 'new'],
 ['KRUMME', 'list_item', 'unrelated', '2', 'new'],
 ['GROLOR', 'crit_lure', 'unrelated', '2', 'new'],
 ['TOLOR', 'list_item', 'unrelated', '2', 'new'],
 ['SWOLOR', 'list_item', 'unrelated', '2', 'new'],
 ['DROLOR', 'list_item', 'unrelated', '2', 'new'],
 ['PROLOR', 'list_item', 'unrelated', '2', 'new'],
 ['CROLOR', 'list_item', 'unrelated', '2', 'new'],
 ['PHOLOR', 'list_item', 'unrelated', '2', 'new'],
 ['PAZY', 'crit_lure', 'unrelated', '2', 'new'],
 ['BAZY', 'list_item', 'unrelated', '2', 'new'],
 ['GRAZY', 'list_item', 'unrelated', '2', 'new'],
 ['PRAZY', 'list_item', 'unrelated', '2', 'new'],
 ['ZAZY', 'list_item', 'unrelated', '2', 'new'],
 ['WAZY', 'list_item', 'unrelated', '2', 'new'],
 ['KAZY', 'list_item', 'unrelated', '2', 'new']]

In [12]:
# study and test lists (version B)
test_b = [['TIFFY', 'crit_lure', 'related', '2', 'new'],
 ['PRIFFY', 'list_item', 'related', '1', 'old'],
 ['TRIFFY', 'list_item', 'related', '1', 'old'],
 ['SIFFY', 'list_item', 'related', '1', 'old'],
 ['BLIFFY', 'list_item', 'related', '1', 'old'],
 ['ZIFFY', 'list_item', 'related', '1', 'old'],
 ['GRIFFY', 'list_item', 'related', '1', 'old'],
 ['VUTER', 'crit_lure', 'related', '2', 'new'],
 ['SNUTER', 'list_item', 'related', '1', 'old'],
 ['PLUTER', 'list_item', 'related', '1', 'old'],
 ['BRUTER', 'list_item', 'related', '1', 'old'],
 ['HUTER', 'list_item', 'related', '1', 'old'],
 ['KLUTER', 'list_item', 'related', '1', 'old'],
 ['CRUTER', 'list_item', 'related', '1', 'old'],
 ['FLEAGLE', 'crit_lure', 'related', '2', 'new'],
 ['KLEAGLE', 'list_item', 'related', '1', 'old'],
 ['CREAGLE', 'list_item', 'related', '1', 'old'],
 ['PLEAGLE', 'list_item', 'related', '1', 'old'],
 ['GREAGLE', 'list_item', 'related', '1', 'old'],
 ['PREAGLE', 'list_item', 'related', '1', 'old'],
 ['SWEAGLE', 'list_item', 'related', '1', 'old'],
 ['ZIQUE', 'crit_lure', 'related', '2', 'new'],
 ['JIQUE', 'list_item', 'related', '1', 'old'],
 ['NIQUE', 'list_item', 'related', '1', 'old'],
 ['SHIQUE', 'list_item', 'related', '1', 'old'],
 ['PLIQUE', 'list_item', 'related', '1', 'old'],
 ['FRIQUE', 'list_item', 'related', '1', 'old'],
 ['WIQUE', 'list_item', 'related', '1', 'old'],
 ['PRUSS', 'crit_lure', 'related', '2', 'new'],
 ['DRUSS', 'list_item', 'related', '1', 'old'],
 ['ZUSS', 'list_item', 'related', '1', 'old'],
 ['NUSS', 'list_item', 'related', '1', 'old'],
 ['KRUSS', 'list_item', 'related', '1', 'old'],
 ['GRUSS', 'list_item', 'related', '1', 'old'],
 ['KUSS', 'list_item', 'related', '1', 'old'],
 ['KATION', 'crit_lure', 'related', '2', 'new'],
 ['FRATION', 'list_item', 'related', '1', 'old'],
 ['JATION', 'list_item', 'related', '1', 'old'],
 ['KRATION', 'list_item', 'related', '1', 'old'],
 ['SNATION', 'list_item', 'related', '1', 'old'],
 ['PLATION', 'list_item', 'related', '1', 'old'],
 ['GRATION', 'list_item', 'related', '1', 'old'],
 ['SWOWEN', 'crit_lure', 'related', '2', 'new'],
 ['KROWEN', 'list_item', 'related', '1', 'old'],
 ['TOWEN', 'list_item', 'related', '1', 'old'],
 ['POWEN', 'list_item', 'related', '1', 'old'],
 ['TROWEN', 'list_item', 'related', '1', 'old'],
 ['CLOWEN', 'list_item', 'related', '1', 'old'],
 ['FROWEN', 'list_item', 'related', '1', 'old'],
 ['KLUMME', 'crit_lure', 'related', '2', 'new'],
 ['DUMME', 'list_item', 'related', '1', 'old'],
 ['GRUMME', 'list_item', 'related', '1', 'old'],
 ['PUMME', 'list_item', 'related', '1', 'old'],
 ['WUMME', 'list_item', 'related', '1', 'old'],
 ['SWUMME', 'list_item', 'related', '1', 'old'],
 ['KRUMME', 'list_item', 'related', '1', 'old'],
 ['GROLOR', 'crit_lure', 'related', '2', 'new'],
 ['TOLOR', 'list_item', 'related', '1', 'old'],
 ['SWOLOR', 'list_item', 'related', '1', 'old'],
 ['DROLOR', 'list_item', 'related', '1', 'old'],
 ['PROLOR', 'list_item', 'related', '1', 'old'],
 ['CROLOR', 'list_item', 'related', '1', 'old'],
 ['PHOLOR', 'list_item', 'related', '1', 'old'],
 ['PAZY', 'crit_lure', 'related', '2', 'new'],
 ['BAZY', 'list_item', 'related', '1', 'old'],
 ['GRAZY', 'list_item', 'related', '1', 'old'],
 ['PRAZY', 'list_item', 'related', '1', 'old'],
 ['ZAZY', 'list_item', 'related', '1', 'old'],
 ['WAZY', 'list_item', 'related', '1', 'old'],
 ['KAZY', 'list_item', 'related', '1', 'old'],
 ['KLENDER', 'crit_lure', 'unrelated', '2', 'new'],
 ['SNENDER', 'list_item', 'unrelated', '2', 'new'],
 ['NENDER', 'list_item', 'unrelated', '2', 'new'],
 ['HENDER', 'list_item', 'unrelated', '2', 'new'],
 ['DENDER', 'list_item', 'unrelated', '2', 'new'],
 ['WENDER', 'list_item', 'unrelated', '2', 'new'],
 ['TRENDER', 'list_item', 'unrelated', '2', 'new'],
 ['DATOP', 'crit_lure', 'unrelated', '2', 'new'],
 ['FRATOP', 'list_item', 'unrelated', '2', 'new'],
 ['SATOP', 'list_item', 'unrelated', '2', 'new'],
 ['DRATOP', 'list_item', 'unrelated', '2', 'new'],
 ['TRATOP', 'list_item', 'unrelated', '2', 'new'],
 ['TATOP', 'list_item', 'unrelated', '2', 'new'],
 ['SNATOP', 'list_item', 'unrelated', '2', 'new'],
 ['KIGIN', 'crit_lure', 'unrelated', '2', 'new'],
 ['DRIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['TIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['PRIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['TRIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['DIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['HIGIN', 'list_item', 'unrelated', '2', 'new'],
 ['VALKY', 'crit_lure', 'unrelated', '2', 'new'],
 ['KLALKY', 'list_item', 'unrelated', '2', 'new'],
 ['PHALKY', 'list_item', 'unrelated', '2', 'new'],
 ['FLALKY', 'list_item', 'unrelated', '2', 'new'],
 ['KRALKY', 'list_item', 'unrelated', '2', 'new'],
 ['PRALKY', 'list_item', 'unrelated', '2', 'new'],
 ['GALKY', 'list_item', 'unrelated', '2', 'new'],
 ['SHEDI', 'crit_lure', 'unrelated', '2', 'new'],
 ['PHEDI', 'list_item', 'unrelated', '2', 'new'],
 ['NEDI', 'list_item', 'unrelated', '2', 'new'],
 ['KEDI', 'list_item', 'unrelated', '2', 'new'],
 ['BREDI', 'list_item', 'unrelated', '2', 'new'],
 ['HEDI', 'list_item', 'unrelated', '2', 'new'],
 ['KLEDI', 'list_item', 'unrelated', '2', 'new'],
 ['PRESKTO', 'crit_lure', 'unrelated', '2', 'new'],
 ['SHESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['JESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['GRESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['MESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['KLESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['SNESKTO', 'list_item', 'unrelated', '2', 'new'],
 ['WECK', 'crit_lure', 'unrelated', '2', 'new'],
 ['CRECK', 'list_item', 'unrelated', '2', 'new'],
 ['BLECK', 'list_item', 'unrelated', '2', 'new'],
 ['FRECK', 'list_item', 'unrelated', '2', 'new'],
 ['BRECK', 'list_item', 'unrelated', '2', 'new'],
 ['SNECK', 'list_item', 'unrelated', '2', 'new'],
 ['TECK', 'list_item', 'unrelated', '2', 'new'],
 ['HAPTE', 'crit_lure', 'unrelated', '2', 'new'],
 ['BAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['DAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['VAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['SWAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['PRAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['BLAPTE', 'list_item', 'unrelated', '2', 'new'],
 ['KLOOM', 'crit_lure', 'unrelated', '2', 'new'],
 ['TROOM', 'list_item', 'unrelated', '2', 'new'],
 ['FROOM', 'list_item', 'unrelated', '2', 'new'],
 ['KROOM', 'list_item', 'unrelated', '2', 'new'],
 ['FLOOM', 'list_item', 'unrelated', '2', 'new'],
 ['SNOOM', 'list_item', 'unrelated', '2', 'new'],
 ['VOOM', 'list_item', 'unrelated', '2', 'new'],
 ['ZAISE', 'crit_lure', 'unrelated', '2', 'new'],
 ['SAISE', 'list_item', 'unrelated', '2', 'new'],
 ['VAISE', 'list_item', 'unrelated', '2', 'new'],
 ['SNAISE', 'list_item', 'unrelated', '2', 'new'],
 ['PAISE', 'list_item', 'unrelated', '2', 'new'],
 ['JAISE', 'list_item', 'unrelated', '2', 'new'],
 ['TAISE', 'list_item', 'unrelated', '2', 'new']]

In [13]:
#function to set up study and test lists
def get_stim_list(clean_df):
    list_rel = [i[0].lower() for i in clean_df if i[1]=='list_item' and i[2]=='related']
    crit_rel = [i[0].lower() for i in clean_df if i[1]=='crit_lure' and i[2]=='related']
    list_new = [i[0].lower() for i in clean_df if i[1]=='list_item' and i[2]=='unrelated']
    crit_new = [i[0].lower() for i in clean_df if i[1]=='crit_lure' and i[2]=='unrelated']
    return list_rel + crit_rel + list_new + crit_new

In [14]:
# normalize matrix before simulation
word_matrix = normalize_matrix(word_matrix)

Simulations

In [15]:
# Empirical Means
emp_means = [0.75442177, 0.66734694, 0.3329932 , 0.32653061]

In [16]:
l = 0.05  # Learning rate
t = 3       # Retrieval exponent
p_old = 54    # Percentage of items to be deemed old
sim_list = []
for s in range(0, 1000):
    if s < 500:
        stims = get_stim_list(test_a)
    else:
        stims = get_stim_list(test_b)
    memory = make_memory(stims[0:60])
    memory *= np.random.choice([0, 1], size=(len(memory), len(memory[0])), p=[1-l, l])
    probes = make_memory(stims)
    familiarities = echo_intensity(probes, memory, tau=t)
    criterion = np.percentile(familiarities, 100-p_old)
    list_rel_hits = np.sum(familiarities[:60] > criterion) / 60
    crit_rel_hits = np.sum(familiarities[60:70] > criterion) / 10
    list_new_hits = np.sum(familiarities[70:130] > criterion) / 60
    crit_new_hits = np.sum(familiarities[130:140] > criterion) / 10
    sim_list.append([list_rel_hits, crit_rel_hits, list_new_hits, crit_new_hits])
means = np.mean(sim_list, axis=0)
sds = np.std(sim_list, axis=0, ddof=1)
print('itemtype:', ['target list/list item', 'target list/critical lure', 'foil list/list item', 'foil list/critical lure'])
print('means: ', means)
print('SDs: ', sds)
print('R-squared fit: ', r_sq(emp_means, means))
print('Empirical means: ', emp_means)

itemtype: ['target list/list item', 'target list/critical lure', 'foil list/list item', 'foil list/critical lure']
means:  [0.74853333 0.6574     0.35851667 0.3003    ]
SDs:  [0.07369948 0.12214811 0.07459504 0.11118576]
R-squared fit:  0.9906360707429855
Empirical means:  [0.75442177, 0.66734694, 0.3329932, 0.32653061]


In [17]:
# loop to find best fitting parameters
para_list = []
t = 3
p_old = 54
for L in range(1, 31, 1):
    l = L / 100
    sim_list = []
    for s in range(0, 1000):
        if s < 500:
            stims = get_stim_list(test_a)
        else:
            stims = get_stim_list(test_b)
        memory = make_memory(stims[0:60])
        memory *= np.random.choice([0, 1], size=(len(memory), len(memory[0])), p=[1-l, l])
        probes = make_memory(stims)
        familiarities = echo_intensity(probes, memory, tau=t)
        criterion = np.percentile(familiarities, 100-p_old)
        list_rel_hits = np.sum(familiarities[:60] > criterion) / 60
        crit_rel_hits = np.sum(familiarities[60:70] > criterion) / 10
        list_new_hits = np.sum(familiarities[70:130] > criterion) / 60
        crit_new_hits = np.sum(familiarities[130:140] > criterion) / 10
        sim_list.append([list_rel_hits, crit_rel_hits, list_new_hits, crit_new_hits])
    sim_mean = np.mean(sim_list, axis=0)
    sim_sd = np.std(sim_list, axis=0, ddof=1)
    rsq_fit = r_sq(sim_mean, emp_means)
    mse_fit = mse(sim_mean, emp_means)
    para_list.append([l, rsq_fit, mse_fit, sim_mean])

In [18]:
def sel_third(x):
    return x[2]

In [19]:
# sort by lowest mean square error
para_list.sort(key=sel_third)

In [20]:
para_list

[[0.05,
  0.9884167451406385,
  0.00046413665162712805,
  array([0.7477 , 0.6544 , 0.36045, 0.2967 ])],
 [0.06,
  0.9919595563476415,
  0.0007045025674049111,
  array([0.77076667, 0.6743    , 0.3374    , 0.2767    ])],
 [0.04,
  0.9870950981656383,
  0.0010128154924049033,
  array([0.72096667, 0.6484    , 0.38365   , 0.3239    ])],
 [0.07,
  0.9961128675148745,
  0.0017943718007660478,
  array([0.79721667, 0.6923    , 0.31046667, 0.2616    ])],
 [0.03,
  0.9796503177009872,
  0.0036649994023215753,
  array([0.68685   , 0.6211    , 0.41678333, 0.3571    ])],
 [0.08,
  0.9974343599128213,
  0.003910133467182733,
  array([0.81976667, 0.7162    , 0.28691667, 0.2437    ])],
 [0.09,
  0.997164310782286,
  0.006615382278655004,
  array([0.83968333, 0.729     , 0.26875   , 0.2204    ])],
 [0.02,
  0.9705447850805837,
  0.007826389339099292,
  array([0.65281667, 0.6068    , 0.44748333, 0.3914    ])],
 [0.1,
  0.9969958749147074,
  0.010276980057821596,
  array([0.85931667, 0.752     , 0.24855  